version: "3.5"

services:
  mongo:
    image: mongo

  mongocrud:
    image: ${DOCKER_REGISTRY-}mongocrud
    build:
      context: .
      dockerfile: MongoCRUD/Dockerfile
    ports:
      - '5000:5000'

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'

  redis:
    image: redis
    ports:
      - '6379:6379'